site_name: iCal4j
site_url: https://www.ical4j.org
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-48.png
  features:
    - content.code.copy
    - navigation.tabs
    
repo_url: https://github.com/ical4j/ical4j-user-guide
repo_name: ical4j/ical4j-user-guide
google_analytics:
  - UA-402774-10
  - auto
extra:
  analytics:
    provider: google
    property: UA-402774-10
  disqus: ical4j
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benfortuna
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
markdown_extensions:
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Home:
    - Introduction: index.md
    - Features:
        - Parameters: parameters.md
        - Properties: properties.md
        - Components: components.md
        - Validation: validation.md
        - Compatibility: compatibility.md
        - Date/Time Concepts: datetime.md
        - Encoding: encoding.md
        - Filtering: filtering.md
        - Groovy: groovy.md
        - Indexing: indexing.md
        - Parsing: parser.md
        - Recurrences: recurrences.md
        - Timezones: timezones.md
        - OSGi: osgi.md
#   - Services:
#     - Overview: services/index.md
    - Getting Started: getting-started.md
    - Configuration: configuring.md
    - Examples:
        - Overview: examples/index.md
        - Parsing: examples/parsing.md
        - Model: examples/model.md
        - Output: examples/output.md
        - Recurrences: examples/recur.md
        - Filtering: examples/filter.md
    - Android: android.md
    - ZoneInfo Outlook: zoneinfo-outlook.md
    - tzurl.org: tzurl.md
    - References:
        - RFC Compliance: rfcs.md
        - CUAs: cuas.md
        - Projects using iCal4j: projects.md
        - Resources: resources.md

  - vCard:
      - Overview: vcard/index.md
      - Examples: vcard/examples.md
  - Extensions:
      - Overview: extensions/index.md
      - CalDAV: extensions/caldav.md
      - Concept:
        - Overview: extensions/concept/index.md
        - Event: extensions/concept/event.md
        - Observance: extensions/concept/observance.md
        - Action: extensions/concept/action.md
        - Issue: extensions/concept/issue.md
        - Request: extensions/concept/request.md
        - Note: extensions/concept/note.md
        - Report: extensions/concept/report.md
        - Availability: extensions/concept/availability.md
      - Link:
        - Overview: extensions/link/index.md
        - Alternate: extensions/link/alternate.md
        - Author: extensions/link/author.md
        - Bookmark: extensions/link/bookmark.md
        - Copyright: extensions/link/copyright.md
        - Edit: extensions/link/edit.md
        - External: extensions/link/external.md
        - Help: extensions/link/help.md
        - Hub: extensions/link/hub.md
        - Icon: extensions/link/icon.md
        - License: extensions/link/license.md
        - Next: extensions/link/next.md
        - Prev: extensions/link/prev.md
        - Related: extensions/link/related.md
        - Replies: extensions/link/replies.md
        - Self: extensions/link/self.md
        - Status: extensions/link/status.md
        - Webmention: extensions/link/webmention.md
      - Participant: extensions/participant.md
      - Outlook: extensions/outlook.md
      - Strategy:
        - Overview: extensions/strategy/index.md
        - Event: extensions/strategy/event.md
        - Observance: extensions/strategy/observance.md
        - Action: extensions/strategy/action.md
        - Issue: extensions/strategy/issue.md
        - Request: extensions/strategy/request.md
        - Note: extensions/strategy/note.md
        - Report: extensions/strategy/report.md
        - Availability: extensions/strategy/availability.md
        - Entity: extensions/strategy/entity.md
  - Connector:
    - Overview: connector/index.md
    - Local: connector/local.md
    - DAV: connector/dav.md
  - Integration:
    - Overview: integration/index.md
    - Email: integration/email.md
    - Websub: integration/websub.md
    - Webhooks: integration/webhooks.md
    - XMPP: integration/xmpp.md
  - Serializer:
    - Overview: serializer/index.md
    - XML: serializer/xml.md
    - JSON: serializer/json.md
    - JSON-LD: serializer/jsonld.md
    - JMAP: serializer/jmap.md
    - JOTN:
      - Overview: serializer/jotn/index.md
      - Alarm: serializer/jotn/alarm.md
      - Availability: serializer/jotn/availability.md
      - Available: serializer/jotn/available.md
      - Calendar: serializer/jotn/calendar.md
      - Card: serializer/jotn/card.md
      - Event: serializer/jotn/event.md
      - Journal: serializer/jotn/journal.md
      - Location: serializer/jotn/location.md
      - Participant: serializer/jotn/participant.md
      - Resource: serializer/jotn/resource.md
      - ToDo: serializer/jotn/todo.md
  - Command:
    - Overview: command/index.md
    - Agent: command/agent.md
    - MCP: command/mcp.md
  - Streams:
    - Overview: streams/index.md
    - Workflow: streams/workflow.md
  - Graph:
      - Overview: graph/index.md
  - Template:
      - Overview: template/index.md
      - Examples: template/examples.md

