site_name: iCal4j
site_url: https://www.ical4j.org
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-48.png
repo_url: https://github.com/ical4j/ical4j-user-guide
repo_name: ical4j/ical4j
google_analytics:
  - UA-402774-10
  - auto
extra:
  analytics:
    provider: google
    property: UA-402774-10
  disqus: ical4j
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benfortuna
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Overview:
    - Introduction: index.md
    - Getting Started: getting-started.md
    - Examples:
        - Overview: examples/overview.md
        - Parsing: examples/parsing.md
        - Model: examples/model.md
        - Output: examples/output.md
        - Recurrences: examples/recur.md
        - Filtering: examples/filter.md
        - VCard: examples/vcard.md
    - Android: android.md
    - Maven: maven.md
  - Features:
    - Validation: validation.md
    - Compatibility: compatibility.md
    - Date/Time Concepts: datetime.md
    - Encoding: encoding.md
    - Filtering: filtering.md
    - Groovy: groovy.md
    - Indexing: indexing.md
    - Parsing: parser.md
    - Recurrences: recurrences.md
    - Timezones: timezones.md
  - iCal4j vCard: vcard.md
  - iCal4j Connector: connector.md
  - iCal4j Extensions: extensions.md
  - iCal4j Integration: integration.md
  - iCal4j Serializer: serializer.md
  - iCal4j Templates: templates.md
  - iCal4j ZoneInfo Outlook: zoneinfo-outlook.md
  - iCal4j Validator: validator.md
  - iCal4j FreeBusy: freebusy.md
  - tzurl.org: tzurl.md
  - References:
    - RFC Compliance: rfcs.md
    - CUAs: cuas.md
    - External Resources: external-resources.md
    - Projects using iCal4j: projects.md
    - Resources: resources.md
    - Roadmap: roadmap.md
  - FAQ: faq.md
